CREATE DATABASE IF NOT EXISTS novel_reader
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE novel_reader;

CREATE TABLE IF NOT EXISTS novels (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NULL,
  source_name VARCHAR(255) NULL,
  cover_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_novels_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chapters (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  novel_id INT UNSIGNED NOT NULL,
  chapter_no INT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  content LONGTEXT NOT NULL,
  word_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_chapter (novel_id, chapter_no),
  CONSTRAINT fk_chapters_novel
    FOREIGN KEY (novel_id) REFERENCES novels(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audio_clips (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  novel_id INT UNSIGNED NOT NULL,
  first_chapter_no INT UNSIGNED NOT NULL,
  last_chapter_no INT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  audio_path VARCHAR(255) NOT NULL,
  provider VARCHAR(64) NULL,
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_audio_clip (novel_id, first_chapter_no, last_chapter_no),
  CONSTRAINT fk_audio_clips_novel
    FOREIGN KEY (novel_id) REFERENCES novels(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
